[workspace]
resolver = "2"
members = [
    "crates/oxider-query-core",
    "crates/oxider-query-macros",
    "crates/oxider-query",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/OxideR-System/OxideR-Query"
authors = ["OxideR System"]

[workspace.dependencies]
oxider-query-core = { path = "crates/oxider-query-core", version = "0.1.0" }
oxider-query-macros = { path = "crates/oxider-query-macros", version = "0.1.0" }
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
