[package]
name = "oxider-query-core"
description = "Dialect-agnostic, type-safe SQL query builder core for OxideR-Query"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "../../README.md"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std", "clock"], optional = true }

[features]
default = ["chrono"]
