import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The guide is a linear sequence of numbered chapters, so the file order in
// `../docs` is the reading order. An autogenerated sidebar keeps the two in
// step without a second list to maintain.
const sidebars: SidebarsConfig = {
  guideSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
